language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t timbutorac/multi-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true timbutorac/multi-docker-react npm run test

after_success:
  - docker build -t timbutorac/multi-client ./client
  - docker build -t timbutorac/multi-nginx ./nginx
  - docker build -t timbutorac/multi-server ./server
  - docker build -t timbutorac/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push timbutorac/multi-client
  - docker push timbutorac/multi-nginx
  - docker push timbutorac/multi-server
  - docker push timbutorac/multi-worker
